version: '3.7'
services:
  keycloak:
    container_name: keycloak-sendinblue
    image: jboss/keycloak:{{ KEYCLOAK_VERSION }}
    ports:
    - 18080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: keycloak
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./target/keycloak-sendinblue-{{ KEYCLOAK_VERSION }}.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-sendinblue.jar
