version: '3.7'
services:
  keycloak:
    container_name: keycloak-sendinblue
    image: "quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}"
    ports:
    - 18080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: keycloak
      SENDINBLUE_API_KEY: none
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./test/email-provider.cli:/opt/jboss/startup-scripts/email-provider.cli
    - "./sendinblue-bundle/target/keycloak-sendinblue-bundle-KC-${KEYCLOAK_VERSION}-docker.ear:/opt/jboss/keycloak/standalone/deployments/keycloak-sendinblue.ear"
